#!/usr/bin/python

# -*- coding: UTF-8 -*-

from os import system, name

import itertools

import threading

import time

import sys

import datetime

from base64 import b64decode,b64encode

from datetime import date

expirydate = datetime.date(2023, 5, 31)

#expirydate = datetime.date(2021, 8, 30)

today=date.today()

green="\033[3;32m"

neon="\033[3;36m"

nc="\033[00m"

red="\033[3;31m"

purple="\033[3;34m"

yellow="\033[3;33m"

voilet="\033[3;35m"

White="\033[3;35m"

Lime="\033[3;32m"

Orange="\033[3;32m"

def hero():

    def chalo():

        done = False

        #here is the animation

        def animate():

            for c in itertools.cycle(['|', '/', '-', '\\']) :

                if done:

                    break

                sys.stdout.write('\rconnecting to server for next colour--------- ' + c)

                sys.stdout.flush()

                time.sleep(0.1)

            sys.stdout.write('\rDone!     ')

        t = threading.Thread(target=animate)

        t.start()

        #long process here

        time.sleep(0.8)

        done = True

    def chalo1():

        done = False

        #here is the animation

        def animate():

            for c in itertools.cycle(['|', '/', '-', '\\']):

                if done:

                    break

                sys.stdout.write('\rgetting the colour wait --------- ' + c)

                sys.stdout.flush()

                time.sleep(0.1)

            sys.stdout.write('\rDone!     ')

        t = threading.Thread(target=animate)

        t.start()

        #long process here

        time.sleep(0.7)

        done = True

    def clear():

        # for windows

        if name == 'nt':

            _ = system('cls')

        # for mac and linux(here, os.name is 'posix')

        else:

            _ = system('clear')

    clear()

    y=1

    newperiod=period

    banner='figlet ROSE|lolcat'

    thisway=[2,6,8,11,12,15,16,18,19,20]

    thatway=[1,3,4,5,7,9,10,14,13,17]

    numbers=[]

    i=1

    while(y):

        clear()

        system(banner)

        print(f"{yellow}Contact me on telegram @UnicHugz")

        

        print(f"{nc}Enter ",newperiod," Sapre Price :")

        

        current=input()

        current=int(current)

        chalo()

        print(f"{Orange}\n---------Successfully Connected to the server-----------")

        chalo1()

        print(f"{Orange}\n---------Successfully got the colour -------------")

        print('\n')

        def getSum(n):

            sum=0

            for digit in str(n):

                sum += int(digit)

            return sum

        if i in thisway:

            m=getSum(current)

            n=int(current)%15

            if((m%2==0 and n%2==0) or (m%2==1 and n%2==1)):

                if current in numbers:

                    print(newperiod+1,f"{green} : 1️⃣ 🟢 7️⃣ 🟢 GREEN")

                else:

                    print(newperiod+1,f"{red} : 2️⃣ 🔴 6️⃣ 🔴 RED")

            else:

                if current in numbers:

                    print(newperiod+1,f"{red} : 3️⃣ 🟢 5️⃣ 🟢green")

                else:

                    print(newperiod+1,f"{green} : 4️⃣ 🔴 8️⃣ 🔴 red" )

        if i in thatway:

            m=getSum(current)+1

            n=int(current)%15

            if((m%2==0 and n%2==0) or (m%2==1 and n%2==1)):

                if current in numbers:

                    print(newperiod+1,f"{red} :6️⃣ 🔴 4️⃣ 🔴 RED")

                else:

                    print(newperiod+1,f"{green}: 5️⃣ 🟢 1️⃣ 🟢 GREEN")

            else:

                if current in numbers:

                    print(newperiod+1,f"{red} : 🔟 🔴 2️⃣ 🔴 RED")

                else:

                    print(newperiod+1,f"{green}:7️⃣ 🟢 9️⃣ 🟢 GREEN")

        i=i+1

        newperiod+=1

        numbers.append(current)

        y=input(f"{yellow}Do you want to play : Press 1 and 0 to exit \n")

        if(y==0):

            y=False

        if (len(numbers)>10):

            clear()

            system('figlet TIME UP|lolcat')

            print(f"{neon}Play on next specified time!!")

            print("-----------Current Time UP----------")

            sys.exit(f"{yellow} \n \n \n Contact on Telegram @UnicHugz")

            print(numbers)

  

if(expirydate>today):

    now = datetime.datetime.now()

    First = now.replace(hour=6, minute=57, second=0, microsecond=0)

    Firstend = now.replace(hour=7, minute=55, second=0, microsecond=0)

    Second = now.replace(hour=9, minute=57, second=0, microsecond=0)

    Secondend = now.replace(hour=10, minute=30, second=0, microsecond=0)

    Third = now.replace(hour=12, minute=57, second=0, microsecond=0)

    Thirdend = now.replace(hour=13, minute=30, second=0, microsecond=0)

    Fourth = now.replace(hour=16, minute=27, second=0, microsecond=0)

    Fourthend = now.replace(hour=17, minute=00, second=0, microsecond=0)

    Fifth = now.replace(hour=19, minute=27, second=0, microsecond=0)

    Fifthend = now.replace(hour=20, minute=00, second=0, microsecond=0)

    Final = now.replace(hour=21, minute=57, second=0, microsecond=0)

    Finalend = now.replace(hour=22, minute=30, second=0, microsecond=0)

    

    if (now>First and now<Firstend):

            period=140

            hero()

    elif(now>Second and now<Secondend):

            period=200

            hero()

    elif(now>Third and now<Thirdend):

            period=260

            hero()

    elif(now>Fourth and now<Fourthend):

            period=330

            hero()

    elif(now>Fifth and now<Fifthend):

            period=390

            hero()

    elif(now>Final and now<Finalend):

            period=430

            hero()

    else:

        banner='figlet PLAY |lolcat'

        system(banner)

        print(f"{voilet}Hi!! Thanks for buying the Tools")

        print(f"{voilet}------Your play time-----------")

        

        print(f"{neon}Today, 07:00 AM- 7:30 AM")

        print(f"{neon}Today, 10:00 AM- 10:30 AM")

        print(f"{neon}Today, 01:00 PM- 01:30 PM")

        print(f"{red}Today, 04:30 PM- 05:00 PM")

        print(f"{neon}Today, 07:30 PM- 08:00 PM")

        print(f"{neon}Today, 09:30 PM- 10:00 PM")

        print("Please play on the given time ")

        print(f"{yellow}admin on telegram @UnicHugz")

else:

    banner='figlet EXPIRED|lolcat'

    system(banner)

    print("*---------*----------*-------------*----------*")

    print(f"{red}Your Tools has expired--- Please contact")

    print(f"{yellow}telegram ----@UnicHugz for activating")

    print(f"{nc}*---------*----------*-------------*----------*")
